#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4_DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_BOOKSTORE")]
	public partial class QLNSModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCONGNO(CONGNO instance);
    partial void UpdateCONGNO(CONGNO instance);
    partial void DeleteCONGNO(CONGNO instance);
    partial void InsertCTHD(CTHD instance);
    partial void UpdateCTHD(CTHD instance);
    partial void DeleteCTHD(CTHD instance);
    partial void InsertCTPN(CTPN instance);
    partial void UpdateCTPN(CTPN instance);
    partial void DeleteCTPN(CTPN instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertPHIEUNHAP(PHIEUNHAP instance);
    partial void UpdatePHIEUNHAP(PHIEUNHAP instance);
    partial void DeletePHIEUNHAP(PHIEUNHAP instance);
    partial void InsertPHIEUTHUTIEN(PHIEUTHUTIEN instance);
    partial void UpdatePHIEUTHUTIEN(PHIEUTHUTIEN instance);
    partial void DeletePHIEUTHUTIEN(PHIEUTHUTIEN instance);
    partial void InsertPHIEUTON(PHIEUTON instance);
    partial void UpdatePHIEUTON(PHIEUTON instance);
    partial void DeletePHIEUTON(PHIEUTON instance);
    partial void InsertSACH(SACH instance);
    partial void UpdateSACH(SACH instance);
    partial void DeleteSACH(SACH instance);
    partial void InsertTHAMSO(THAMSO instance);
    partial void UpdateTHAMSO(THAMSO instance);
    partial void DeleteTHAMSO(THAMSO instance);
    #endregion
		
		public QLNSModelDataContext() : 
				base(global::_4_DTO.Properties.Settings.Default.QL_BOOKSTOREConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CONGNO> CONGNOs
		{
			get
			{
				return this.GetTable<CONGNO>();
			}
		}
		
		public System.Data.Linq.Table<CTHD> CTHDs
		{
			get
			{
				return this.GetTable<CTHD>();
			}
		}
		
		public System.Data.Linq.Table<CTPN> CTPNs
		{
			get
			{
				return this.GetTable<CTPN>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUNHAP> PHIEUNHAPs
		{
			get
			{
				return this.GetTable<PHIEUNHAP>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUTHUTIEN> PHIEUTHUTIENs
		{
			get
			{
				return this.GetTable<PHIEUTHUTIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUTON> PHIEUTONs
		{
			get
			{
				return this.GetTable<PHIEUTON>();
			}
		}
		
		public System.Data.Linq.Table<SACH> SACHes
		{
			get
			{
				return this.GetTable<SACH>();
			}
		}
		
		public System.Data.Linq.Table<THAMSO> THAMSOs
		{
			get
			{
				return this.GetTable<THAMSO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONGNO")]
	public partial class CONGNO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCongNo;
		
		private string _MaKH;
		
		private System.Nullable<int> _Thang;
		
		private System.Nullable<decimal> _NoDau;
		
		private System.Nullable<decimal> _NoPhatSinh;
		
		private System.Nullable<decimal> _NoCuoi;
		
		private bool _XoaDuLieu;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCongNoChanging(string value);
    partial void OnMaCongNoChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnThangChanging(System.Nullable<int> value);
    partial void OnThangChanged();
    partial void OnNoDauChanging(System.Nullable<decimal> value);
    partial void OnNoDauChanged();
    partial void OnNoPhatSinhChanging(System.Nullable<decimal> value);
    partial void OnNoPhatSinhChanged();
    partial void OnNoCuoiChanging(System.Nullable<decimal> value);
    partial void OnNoCuoiChanged();
    partial void OnXoaDuLieuChanging(bool value);
    partial void OnXoaDuLieuChanged();
    #endregion
		
		public CONGNO()
		{
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongNo", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCongNo
		{
			get
			{
				return this._MaCongNo;
			}
			set
			{
				if ((this._MaCongNo != value))
				{
					this.OnMaCongNoChanging(value);
					this.SendPropertyChanging();
					this._MaCongNo = value;
					this.SendPropertyChanged("MaCongNo");
					this.OnMaCongNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(10)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int")]
		public System.Nullable<int> Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this.OnThangChanging(value);
					this.SendPropertyChanging();
					this._Thang = value;
					this.SendPropertyChanged("Thang");
					this.OnThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoDau", DbType="Money")]
		public System.Nullable<decimal> NoDau
		{
			get
			{
				return this._NoDau;
			}
			set
			{
				if ((this._NoDau != value))
				{
					this.OnNoDauChanging(value);
					this.SendPropertyChanging();
					this._NoDau = value;
					this.SendPropertyChanged("NoDau");
					this.OnNoDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoPhatSinh", DbType="Money")]
		public System.Nullable<decimal> NoPhatSinh
		{
			get
			{
				return this._NoPhatSinh;
			}
			set
			{
				if ((this._NoPhatSinh != value))
				{
					this.OnNoPhatSinhChanging(value);
					this.SendPropertyChanging();
					this._NoPhatSinh = value;
					this.SendPropertyChanged("NoPhatSinh");
					this.OnNoPhatSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoCuoi", DbType="Money")]
		public System.Nullable<decimal> NoCuoi
		{
			get
			{
				return this._NoCuoi;
			}
			set
			{
				if ((this._NoCuoi != value))
				{
					this.OnNoCuoiChanging(value);
					this.SendPropertyChanging();
					this._NoCuoi = value;
					this.SendPropertyChanged("NoCuoi");
					this.OnNoCuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaDuLieu", DbType="Bit NOT NULL")]
		public bool XoaDuLieu
		{
			get
			{
				return this._XoaDuLieu;
			}
			set
			{
				if ((this._XoaDuLieu != value))
				{
					this.OnXoaDuLieuChanging(value);
					this.SendPropertyChanging();
					this._XoaDuLieu = value;
					this.SendPropertyChanged("XoaDuLieu");
					this.OnXoaDuLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_CONGNO", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.CONGNOs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.CONGNOs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTHD")]
	public partial class CTHD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACTHD;
		
		private string _MaSach;
		
		private string _MaHD;
		
		private System.Nullable<int> _SL_BAN;
		
		private bool _XoaDuLieu;
		
		private EntityRef<HOADON> _HOADON;
		
		private EntityRef<SACH> _SACH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACTHDChanging(string value);
    partial void OnMACTHDChanged();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnSL_BANChanging(System.Nullable<int> value);
    partial void OnSL_BANChanged();
    partial void OnXoaDuLieuChanging(bool value);
    partial void OnXoaDuLieuChanged();
    #endregion
		
		public CTHD()
		{
			this._HOADON = default(EntityRef<HOADON>);
			this._SACH = default(EntityRef<SACH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACTHD", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACTHD
		{
			get
			{
				return this._MACTHD;
			}
			set
			{
				if ((this._MACTHD != value))
				{
					this.OnMACTHDChanging(value);
					this.SendPropertyChanging();
					this._MACTHD = value;
					this.SendPropertyChanged("MACTHD");
					this.OnMACTHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="Char(10)")]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					if (this._SACH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="Char(10)")]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					if (this._HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL_BAN", DbType="Int")]
		public System.Nullable<int> SL_BAN
		{
			get
			{
				return this._SL_BAN;
			}
			set
			{
				if ((this._SL_BAN != value))
				{
					this.OnSL_BANChanging(value);
					this.SendPropertyChanging();
					this._SL_BAN = value;
					this.SendPropertyChanged("SL_BAN");
					this.OnSL_BANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaDuLieu", DbType="Bit NOT NULL")]
		public bool XoaDuLieu
		{
			get
			{
				return this._XoaDuLieu;
			}
			set
			{
				if ((this._XoaDuLieu != value))
				{
					this.OnXoaDuLieuChanging(value);
					this.SendPropertyChanging();
					this._XoaDuLieu = value;
					this.SendPropertyChanged("XoaDuLieu");
					this.OnXoaDuLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CTHD", Storage="_HOADON", ThisKey="MaHD", OtherKey="MaHD", IsForeignKey=true)]
		public HOADON HOADON
		{
			get
			{
				return this._HOADON.Entity;
			}
			set
			{
				HOADON previousValue = this._HOADON.Entity;
				if (((previousValue != value) 
							|| (this._HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADON.Entity = null;
						previousValue.CTHDs.Remove(this);
					}
					this._HOADON.Entity = value;
					if ((value != null))
					{
						value.CTHDs.Add(this);
						this._MaHD = value.MaHD;
					}
					else
					{
						this._MaHD = default(string);
					}
					this.SendPropertyChanged("HOADON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SACH_CTHD", Storage="_SACH", ThisKey="MaSach", OtherKey="MaSach", IsForeignKey=true)]
		public SACH SACH
		{
			get
			{
				return this._SACH.Entity;
			}
			set
			{
				SACH previousValue = this._SACH.Entity;
				if (((previousValue != value) 
							|| (this._SACH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SACH.Entity = null;
						previousValue.CTHDs.Remove(this);
					}
					this._SACH.Entity = value;
					if ((value != null))
					{
						value.CTHDs.Add(this);
						this._MaSach = value.MaSach;
					}
					else
					{
						this._MaSach = default(string);
					}
					this.SendPropertyChanged("SACH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPN")]
	public partial class CTPN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCTPN;
		
		private string _MaPN;
		
		private string _MaSach;
		
		private System.Nullable<int> _SL_Nhap;
		
		private bool _XoaDuLieu;
		
		private EntityRef<PHIEUNHAP> _PHIEUNHAP;
		
		private EntityRef<SACH> _SACH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTPNChanging(string value);
    partial void OnMaCTPNChanged();
    partial void OnMaPNChanging(string value);
    partial void OnMaPNChanged();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    partial void OnSL_NhapChanging(System.Nullable<int> value);
    partial void OnSL_NhapChanged();
    partial void OnXoaDuLieuChanging(bool value);
    partial void OnXoaDuLieuChanged();
    #endregion
		
		public CTPN()
		{
			this._PHIEUNHAP = default(EntityRef<PHIEUNHAP>);
			this._SACH = default(EntityRef<SACH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTPN", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCTPN
		{
			get
			{
				return this._MaCTPN;
			}
			set
			{
				if ((this._MaCTPN != value))
				{
					this.OnMaCTPNChanging(value);
					this.SendPropertyChanging();
					this._MaCTPN = value;
					this.SendPropertyChanged("MaCTPN");
					this.OnMaCTPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPN", DbType="Char(10)")]
		public string MaPN
		{
			get
			{
				return this._MaPN;
			}
			set
			{
				if ((this._MaPN != value))
				{
					if (this._PHIEUNHAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPNChanging(value);
					this.SendPropertyChanging();
					this._MaPN = value;
					this.SendPropertyChanged("MaPN");
					this.OnMaPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="Char(10)")]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					if (this._SACH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL_Nhap", DbType="Int")]
		public System.Nullable<int> SL_Nhap
		{
			get
			{
				return this._SL_Nhap;
			}
			set
			{
				if ((this._SL_Nhap != value))
				{
					this.OnSL_NhapChanging(value);
					this.SendPropertyChanging();
					this._SL_Nhap = value;
					this.SendPropertyChanged("SL_Nhap");
					this.OnSL_NhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaDuLieu", DbType="Bit NOT NULL")]
		public bool XoaDuLieu
		{
			get
			{
				return this._XoaDuLieu;
			}
			set
			{
				if ((this._XoaDuLieu != value))
				{
					this.OnXoaDuLieuChanging(value);
					this.SendPropertyChanging();
					this._XoaDuLieu = value;
					this.SendPropertyChanged("XoaDuLieu");
					this.OnXoaDuLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAP_CTPN", Storage="_PHIEUNHAP", ThisKey="MaPN", OtherKey="MaPN", IsForeignKey=true)]
		public PHIEUNHAP PHIEUNHAP
		{
			get
			{
				return this._PHIEUNHAP.Entity;
			}
			set
			{
				PHIEUNHAP previousValue = this._PHIEUNHAP.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUNHAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUNHAP.Entity = null;
						previousValue.CTPNs.Remove(this);
					}
					this._PHIEUNHAP.Entity = value;
					if ((value != null))
					{
						value.CTPNs.Add(this);
						this._MaPN = value.MaPN;
					}
					else
					{
						this._MaPN = default(string);
					}
					this.SendPropertyChanged("PHIEUNHAP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SACH_CTPN", Storage="_SACH", ThisKey="MaSach", OtherKey="MaSach", IsForeignKey=true)]
		public SACH SACH
		{
			get
			{
				return this._SACH.Entity;
			}
			set
			{
				SACH previousValue = this._SACH.Entity;
				if (((previousValue != value) 
							|| (this._SACH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SACH.Entity = null;
						previousValue.CTPNs.Remove(this);
					}
					this._SACH.Entity = value;
					if ((value != null))
					{
						value.CTPNs.Add(this);
						this._MaSach = value.MaSach;
					}
					else
					{
						this._MaSach = default(string);
					}
					this.SendPropertyChanged("SACH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private string _MaKH;
		
		private System.Nullable<System.DateTime> _NgayHD;
		
		private bool _XoaDuLieu;
		
		private EntitySet<CTHD> _CTHDs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnNgayHDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHDChanged();
    partial void OnXoaDuLieuChanging(bool value);
    partial void OnXoaDuLieuChanged();
    #endregion
		
		public HOADON()
		{
			this._CTHDs = new EntitySet<CTHD>(new Action<CTHD>(this.attach_CTHDs), new Action<CTHD>(this.detach_CTHDs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(10)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHD", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayHD
		{
			get
			{
				return this._NgayHD;
			}
			set
			{
				if ((this._NgayHD != value))
				{
					this.OnNgayHDChanging(value);
					this.SendPropertyChanging();
					this._NgayHD = value;
					this.SendPropertyChanged("NgayHD");
					this.OnNgayHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaDuLieu", DbType="Bit NOT NULL")]
		public bool XoaDuLieu
		{
			get
			{
				return this._XoaDuLieu;
			}
			set
			{
				if ((this._XoaDuLieu != value))
				{
					this.OnXoaDuLieuChanging(value);
					this.SendPropertyChanging();
					this._XoaDuLieu = value;
					this.SendPropertyChanged("XoaDuLieu");
					this.OnXoaDuLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CTHD", Storage="_CTHDs", ThisKey="MaHD", OtherKey="MaHD")]
		public EntitySet<CTHD> CTHDs
		{
			get
			{
				return this._CTHDs;
			}
			set
			{
				this._CTHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = this;
		}
		
		private void detach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private string _Email;
		
		private System.Nullable<decimal> _SoTienNo;
		
		private bool _XoaDuLieu;
		
		private EntitySet<CONGNO> _CONGNOs;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntitySet<PHIEUTHUTIEN> _PHIEUTHUTIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSoTienNoChanging(System.Nullable<decimal> value);
    partial void OnSoTienNoChanged();
    partial void OnXoaDuLieuChanging(bool value);
    partial void OnXoaDuLieuChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._CONGNOs = new EntitySet<CONGNO>(new Action<CONGNO>(this.attach_CONGNOs), new Action<CONGNO>(this.detach_CONGNOs));
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._PHIEUTHUTIENs = new EntitySet<PHIEUTHUTIEN>(new Action<PHIEUTHUTIEN>(this.attach_PHIEUTHUTIENs), new Action<PHIEUTHUTIEN>(this.detach_PHIEUTHUTIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NVarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienNo", DbType="Money")]
		public System.Nullable<decimal> SoTienNo
		{
			get
			{
				return this._SoTienNo;
			}
			set
			{
				if ((this._SoTienNo != value))
				{
					this.OnSoTienNoChanging(value);
					this.SendPropertyChanging();
					this._SoTienNo = value;
					this.SendPropertyChanged("SoTienNo");
					this.OnSoTienNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaDuLieu", DbType="Bit NOT NULL")]
		public bool XoaDuLieu
		{
			get
			{
				return this._XoaDuLieu;
			}
			set
			{
				if ((this._XoaDuLieu != value))
				{
					this.OnXoaDuLieuChanging(value);
					this.SendPropertyChanging();
					this._XoaDuLieu = value;
					this.SendPropertyChanged("XoaDuLieu");
					this.OnXoaDuLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_CONGNO", Storage="_CONGNOs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<CONGNO> CONGNOs
		{
			get
			{
				return this._CONGNOs;
			}
			set
			{
				this._CONGNOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_HOADONs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEUTHUTIEN", Storage="_PHIEUTHUTIENs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<PHIEUTHUTIEN> PHIEUTHUTIENs
		{
			get
			{
				return this._PHIEUTHUTIENs;
			}
			set
			{
				this._PHIEUTHUTIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CONGNOs(CONGNO entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_CONGNOs(CONGNO entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_PHIEUTHUTIENs(PHIEUTHUTIEN entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_PHIEUTHUTIENs(PHIEUTHUTIEN entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUNHAP")]
	public partial class PHIEUNHAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPN;
		
		private System.Nullable<System.DateTime> _NgayNhap;
		
		private bool _XoaDuLieu;
		
		private EntitySet<CTPN> _CTPNs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPNChanging(string value);
    partial void OnMaPNChanged();
    partial void OnNgayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhapChanged();
    partial void OnXoaDuLieuChanging(bool value);
    partial void OnXoaDuLieuChanged();
    #endregion
		
		public PHIEUNHAP()
		{
			this._CTPNs = new EntitySet<CTPN>(new Action<CTPN>(this.attach_CTPNs), new Action<CTPN>(this.detach_CTPNs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPN", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPN
		{
			get
			{
				return this._MaPN;
			}
			set
			{
				if ((this._MaPN != value))
				{
					this.OnMaPNChanging(value);
					this.SendPropertyChanging();
					this._MaPN = value;
					this.SendPropertyChanged("MaPN");
					this.OnMaPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaDuLieu", DbType="Bit NOT NULL")]
		public bool XoaDuLieu
		{
			get
			{
				return this._XoaDuLieu;
			}
			set
			{
				if ((this._XoaDuLieu != value))
				{
					this.OnXoaDuLieuChanging(value);
					this.SendPropertyChanging();
					this._XoaDuLieu = value;
					this.SendPropertyChanged("XoaDuLieu");
					this.OnXoaDuLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAP_CTPN", Storage="_CTPNs", ThisKey="MaPN", OtherKey="MaPN")]
		public EntitySet<CTPN> CTPNs
		{
			get
			{
				return this._CTPNs;
			}
			set
			{
				this._CTPNs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPNs(CTPN entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUNHAP = this;
		}
		
		private void detach_CTPNs(CTPN entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUNHAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUTHUTIEN")]
	public partial class PHIEUTHUTIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThuTien;
		
		private string _MaKH;
		
		private System.Nullable<System.DateTime> _NgayThu;
		
		private System.Nullable<decimal> _SoTienThu;
		
		private bool _XoaDuLieu;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThuTienChanging(string value);
    partial void OnMaThuTienChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnNgayThuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThuChanged();
    partial void OnSoTienThuChanging(System.Nullable<decimal> value);
    partial void OnSoTienThuChanged();
    partial void OnXoaDuLieuChanging(bool value);
    partial void OnXoaDuLieuChanged();
    #endregion
		
		public PHIEUTHUTIEN()
		{
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuTien", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThuTien
		{
			get
			{
				return this._MaThuTien;
			}
			set
			{
				if ((this._MaThuTien != value))
				{
					this.OnMaThuTienChanging(value);
					this.SendPropertyChanging();
					this._MaThuTien = value;
					this.SendPropertyChanged("MaThuTien");
					this.OnMaThuTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(10)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThu", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayThu
		{
			get
			{
				return this._NgayThu;
			}
			set
			{
				if ((this._NgayThu != value))
				{
					this.OnNgayThuChanging(value);
					this.SendPropertyChanging();
					this._NgayThu = value;
					this.SendPropertyChanged("NgayThu");
					this.OnNgayThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienThu", DbType="Money")]
		public System.Nullable<decimal> SoTienThu
		{
			get
			{
				return this._SoTienThu;
			}
			set
			{
				if ((this._SoTienThu != value))
				{
					this.OnSoTienThuChanging(value);
					this.SendPropertyChanging();
					this._SoTienThu = value;
					this.SendPropertyChanged("SoTienThu");
					this.OnSoTienThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaDuLieu", DbType="Bit NOT NULL")]
		public bool XoaDuLieu
		{
			get
			{
				return this._XoaDuLieu;
			}
			set
			{
				if ((this._XoaDuLieu != value))
				{
					this.OnXoaDuLieuChanging(value);
					this.SendPropertyChanging();
					this._XoaDuLieu = value;
					this.SendPropertyChanged("XoaDuLieu");
					this.OnXoaDuLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_PHIEUTHUTIEN", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.PHIEUTHUTIENs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.PHIEUTHUTIENs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUTON")]
	public partial class PHIEUTON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTon;
		
		private string _MaSach;
		
		private System.Nullable<int> _Thang;
		
		private System.Nullable<int> _TonDau;
		
		private System.Nullable<int> _TonPhatSinh;
		
		private System.Nullable<int> _TonCuoi;
		
		private bool _XoaDuLieu;
		
		private EntityRef<SACH> _SACH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTonChanging(string value);
    partial void OnMaTonChanged();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    partial void OnThangChanging(System.Nullable<int> value);
    partial void OnThangChanged();
    partial void OnTonDauChanging(System.Nullable<int> value);
    partial void OnTonDauChanged();
    partial void OnTonPhatSinhChanging(System.Nullable<int> value);
    partial void OnTonPhatSinhChanged();
    partial void OnTonCuoiChanging(System.Nullable<int> value);
    partial void OnTonCuoiChanged();
    partial void OnXoaDuLieuChanging(bool value);
    partial void OnXoaDuLieuChanged();
    #endregion
		
		public PHIEUTON()
		{
			this._SACH = default(EntityRef<SACH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTon", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTon
		{
			get
			{
				return this._MaTon;
			}
			set
			{
				if ((this._MaTon != value))
				{
					this.OnMaTonChanging(value);
					this.SendPropertyChanging();
					this._MaTon = value;
					this.SendPropertyChanged("MaTon");
					this.OnMaTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="Char(10)")]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					if (this._SACH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int")]
		public System.Nullable<int> Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this.OnThangChanging(value);
					this.SendPropertyChanging();
					this._Thang = value;
					this.SendPropertyChanged("Thang");
					this.OnThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonDau", DbType="Int")]
		public System.Nullable<int> TonDau
		{
			get
			{
				return this._TonDau;
			}
			set
			{
				if ((this._TonDau != value))
				{
					this.OnTonDauChanging(value);
					this.SendPropertyChanging();
					this._TonDau = value;
					this.SendPropertyChanged("TonDau");
					this.OnTonDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonPhatSinh", DbType="Int")]
		public System.Nullable<int> TonPhatSinh
		{
			get
			{
				return this._TonPhatSinh;
			}
			set
			{
				if ((this._TonPhatSinh != value))
				{
					this.OnTonPhatSinhChanging(value);
					this.SendPropertyChanging();
					this._TonPhatSinh = value;
					this.SendPropertyChanged("TonPhatSinh");
					this.OnTonPhatSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonCuoi", DbType="Int")]
		public System.Nullable<int> TonCuoi
		{
			get
			{
				return this._TonCuoi;
			}
			set
			{
				if ((this._TonCuoi != value))
				{
					this.OnTonCuoiChanging(value);
					this.SendPropertyChanging();
					this._TonCuoi = value;
					this.SendPropertyChanged("TonCuoi");
					this.OnTonCuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaDuLieu", DbType="Bit NOT NULL")]
		public bool XoaDuLieu
		{
			get
			{
				return this._XoaDuLieu;
			}
			set
			{
				if ((this._XoaDuLieu != value))
				{
					this.OnXoaDuLieuChanging(value);
					this.SendPropertyChanging();
					this._XoaDuLieu = value;
					this.SendPropertyChanged("XoaDuLieu");
					this.OnXoaDuLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SACH_PHIEUTON", Storage="_SACH", ThisKey="MaSach", OtherKey="MaSach", IsForeignKey=true)]
		public SACH SACH
		{
			get
			{
				return this._SACH.Entity;
			}
			set
			{
				SACH previousValue = this._SACH.Entity;
				if (((previousValue != value) 
							|| (this._SACH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SACH.Entity = null;
						previousValue.PHIEUTONs.Remove(this);
					}
					this._SACH.Entity = value;
					if ((value != null))
					{
						value.PHIEUTONs.Add(this);
						this._MaSach = value.MaSach;
					}
					else
					{
						this._MaSach = default(string);
					}
					this.SendPropertyChanged("SACH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SACH")]
	public partial class SACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSach;
		
		private string _TenSach;
		
		private string _TheLoai;
		
		private string _TacGia;
		
		private System.Nullable<int> _SL_Ton;
		
		private System.Nullable<decimal> _DonGia;
		
		private bool _XoaDuLieu;
		
		private EntitySet<CTHD> _CTHDs;
		
		private EntitySet<CTPN> _CTPNs;
		
		private EntitySet<PHIEUTON> _PHIEUTONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    partial void OnTenSachChanging(string value);
    partial void OnTenSachChanged();
    partial void OnTheLoaiChanging(string value);
    partial void OnTheLoaiChanged();
    partial void OnTacGiaChanging(string value);
    partial void OnTacGiaChanged();
    partial void OnSL_TonChanging(System.Nullable<int> value);
    partial void OnSL_TonChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    partial void OnXoaDuLieuChanging(bool value);
    partial void OnXoaDuLieuChanged();
    #endregion
		
		public SACH()
		{
			this._CTHDs = new EntitySet<CTHD>(new Action<CTHD>(this.attach_CTHDs), new Action<CTHD>(this.detach_CTHDs));
			this._CTPNs = new EntitySet<CTPN>(new Action<CTPN>(this.attach_CTPNs), new Action<CTPN>(this.detach_CTPNs));
			this._PHIEUTONs = new EntitySet<PHIEUTON>(new Action<PHIEUTON>(this.attach_PHIEUTONs), new Action<PHIEUTON>(this.detach_PHIEUTONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(100)")]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this.OnTenSachChanging(value);
					this.SendPropertyChanging();
					this._TenSach = value;
					this.SendPropertyChanged("TenSach");
					this.OnTenSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheLoai", DbType="NVarChar(50)")]
		public string TheLoai
		{
			get
			{
				return this._TheLoai;
			}
			set
			{
				if ((this._TheLoai != value))
				{
					this.OnTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._TheLoai = value;
					this.SendPropertyChanged("TheLoai");
					this.OnTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TacGia", DbType="NVarChar(100)")]
		public string TacGia
		{
			get
			{
				return this._TacGia;
			}
			set
			{
				if ((this._TacGia != value))
				{
					this.OnTacGiaChanging(value);
					this.SendPropertyChanging();
					this._TacGia = value;
					this.SendPropertyChanged("TacGia");
					this.OnTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL_Ton", DbType="Int")]
		public System.Nullable<int> SL_Ton
		{
			get
			{
				return this._SL_Ton;
			}
			set
			{
				if ((this._SL_Ton != value))
				{
					this.OnSL_TonChanging(value);
					this.SendPropertyChanging();
					this._SL_Ton = value;
					this.SendPropertyChanged("SL_Ton");
					this.OnSL_TonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaDuLieu", DbType="Bit NOT NULL")]
		public bool XoaDuLieu
		{
			get
			{
				return this._XoaDuLieu;
			}
			set
			{
				if ((this._XoaDuLieu != value))
				{
					this.OnXoaDuLieuChanging(value);
					this.SendPropertyChanging();
					this._XoaDuLieu = value;
					this.SendPropertyChanged("XoaDuLieu");
					this.OnXoaDuLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SACH_CTHD", Storage="_CTHDs", ThisKey="MaSach", OtherKey="MaSach")]
		public EntitySet<CTHD> CTHDs
		{
			get
			{
				return this._CTHDs;
			}
			set
			{
				this._CTHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SACH_CTPN", Storage="_CTPNs", ThisKey="MaSach", OtherKey="MaSach")]
		public EntitySet<CTPN> CTPNs
		{
			get
			{
				return this._CTPNs;
			}
			set
			{
				this._CTPNs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SACH_PHIEUTON", Storage="_PHIEUTONs", ThisKey="MaSach", OtherKey="MaSach")]
		public EntitySet<PHIEUTON> PHIEUTONs
		{
			get
			{
				return this._PHIEUTONs;
			}
			set
			{
				this._PHIEUTONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.SACH = this;
		}
		
		private void detach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.SACH = null;
		}
		
		private void attach_CTPNs(CTPN entity)
		{
			this.SendPropertyChanging();
			entity.SACH = this;
		}
		
		private void detach_CTPNs(CTPN entity)
		{
			this.SendPropertyChanging();
			entity.SACH = null;
		}
		
		private void attach_PHIEUTONs(PHIEUTON entity)
		{
			this.SendPropertyChanging();
			entity.SACH = this;
		}
		
		private void detach_PHIEUTONs(PHIEUTON entity)
		{
			this.SendPropertyChanging();
			entity.SACH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THAMSO")]
	public partial class THAMSO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _SL_NhapItNhat;
		
		private System.Nullable<int> _SL_TonToiDaTruocNhap;
		
		private System.Nullable<int> _SL_TonSauToiThieu;
		
		private System.Nullable<decimal> _SoTienNoToiDa;
		
		private System.Nullable<bool> _SuDungQuyDinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSL_NhapItNhatChanging(System.Nullable<int> value);
    partial void OnSL_NhapItNhatChanged();
    partial void OnSL_TonToiDaTruocNhapChanging(System.Nullable<int> value);
    partial void OnSL_TonToiDaTruocNhapChanged();
    partial void OnSL_TonSauToiThieuChanging(System.Nullable<int> value);
    partial void OnSL_TonSauToiThieuChanged();
    partial void OnSoTienNoToiDaChanging(System.Nullable<decimal> value);
    partial void OnSoTienNoToiDaChanged();
    partial void OnSuDungQuyDinhChanging(System.Nullable<bool> value);
    partial void OnSuDungQuyDinhChanged();
    #endregion
		
		public THAMSO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL_NhapItNhat", DbType="Int")]
		public System.Nullable<int> SL_NhapItNhat
		{
			get
			{
				return this._SL_NhapItNhat;
			}
			set
			{
				if ((this._SL_NhapItNhat != value))
				{
					this.OnSL_NhapItNhatChanging(value);
					this.SendPropertyChanging();
					this._SL_NhapItNhat = value;
					this.SendPropertyChanged("SL_NhapItNhat");
					this.OnSL_NhapItNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL_TonToiDaTruocNhap", DbType="Int")]
		public System.Nullable<int> SL_TonToiDaTruocNhap
		{
			get
			{
				return this._SL_TonToiDaTruocNhap;
			}
			set
			{
				if ((this._SL_TonToiDaTruocNhap != value))
				{
					this.OnSL_TonToiDaTruocNhapChanging(value);
					this.SendPropertyChanging();
					this._SL_TonToiDaTruocNhap = value;
					this.SendPropertyChanged("SL_TonToiDaTruocNhap");
					this.OnSL_TonToiDaTruocNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL_TonSauToiThieu", DbType="Int")]
		public System.Nullable<int> SL_TonSauToiThieu
		{
			get
			{
				return this._SL_TonSauToiThieu;
			}
			set
			{
				if ((this._SL_TonSauToiThieu != value))
				{
					this.OnSL_TonSauToiThieuChanging(value);
					this.SendPropertyChanging();
					this._SL_TonSauToiThieu = value;
					this.SendPropertyChanged("SL_TonSauToiThieu");
					this.OnSL_TonSauToiThieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienNoToiDa", DbType="Money")]
		public System.Nullable<decimal> SoTienNoToiDa
		{
			get
			{
				return this._SoTienNoToiDa;
			}
			set
			{
				if ((this._SoTienNoToiDa != value))
				{
					this.OnSoTienNoToiDaChanging(value);
					this.SendPropertyChanging();
					this._SoTienNoToiDa = value;
					this.SendPropertyChanged("SoTienNoToiDa");
					this.OnSoTienNoToiDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuDungQuyDinh", DbType="Bit")]
		public System.Nullable<bool> SuDungQuyDinh
		{
			get
			{
				return this._SuDungQuyDinh;
			}
			set
			{
				if ((this._SuDungQuyDinh != value))
				{
					this.OnSuDungQuyDinhChanging(value);
					this.SendPropertyChanging();
					this._SuDungQuyDinh = value;
					this.SendPropertyChanged("SuDungQuyDinh");
					this.OnSuDungQuyDinhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
