<?xml version="1.0" encoding="utf-8"?><Database Name="QL_BOOKSTORE" Class="QLNSModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QL_BOOKSTORE;Integrated Security=True" SettingsObjectName="_4_DTO.Properties.Settings" SettingsPropertyName="QL_BOOKSTOREConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TON" Member="TONs">
    <Type Name="TON">
      <Column Name="MATON" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="THANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONDAU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONPHATSINH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONCUOI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="SACH_TON" Member="SACH" ThisKey="MASACH" OtherKey="MASACH" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONGNO" Member="CONGNOs">
    <Type Name="CONGNO">
      <Column Name="MACONGNO" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="THANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NODAU" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NOPHATSINH" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NOCUOI" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="KHACHHANG_CONGNO" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTHD" Member="CTHDs">
    <Type Name="CTHD">
      <Column Name="MACTHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASACH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MAHD" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="SL_BAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADON_CTHD" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="SACH_CTHD" Member="SACH" ThisKey="MASACH" OtherKey="MASACH" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTPN" Member="CTPNs">
    <Type Name="CTPN">
      <Column Name="MACTPN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPN" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="SL_NHAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NHAP_CTPN" Member="NHAP" ThisKey="MAPN" OtherKey="MAPN" Type="NHAP" IsForeignKey="true" />
      <Association Name="SACH_CTPN" Member="SACH" ThisKey="MASACH" OtherKey="MASACH" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="NGAYHD" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="HOADON_CTHD" Member="CTHDs" ThisKey="MAHD" OtherKey="MAHD" Type="CTHD" />
      <Association Name="KHACHHANG_HOADON" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOTIENNO" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="KHACHHANG_CONGNO" Member="CONGNOs" ThisKey="MAKH" OtherKey="MAKH" Type="CONGNO" />
      <Association Name="KHACHHANG_HOADON" Member="HOADONs" ThisKey="MAKH" OtherKey="MAKH" Type="HOADON" />
      <Association Name="KHACHHANG_THUTIEN" Member="THUTIENs" ThisKey="MAKH" OtherKey="MAKH" Type="THUTIEN" />
    </Type>
  </Table>
  <Table Name="dbo.NHAP" Member="NHAPs">
    <Type Name="NHAP">
      <Column Name="MAPN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYNHAP" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="NHAP_CTPN" Member="CTPNs" ThisKey="MAPN" OtherKey="MAPN" Type="CTPN" />
    </Type>
  </Table>
  <Table Name="dbo.SACH" Member="SACHes">
    <Type Name="SACH">
      <Column Name="MASACH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="THELOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TACGIA" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SL_TON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="SACH_TON" Member="TONs" ThisKey="MASACH" OtherKey="MASACH" Type="TON" />
      <Association Name="SACH_CTHD" Member="CTHDs" ThisKey="MASACH" OtherKey="MASACH" Type="CTHD" />
      <Association Name="SACH_CTPN" Member="CTPNs" ThisKey="MASACH" OtherKey="MASACH" Type="CTPN" />
    </Type>
  </Table>
  <Table Name="dbo.THAMSO" Member="THAMSOs">
    <Type Name="THAMSO">
      <Column Name="SL_NHAPITNHAT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SL_TONTOIDATRUOCNHAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SL_TONSAUTOITHIEU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOTIENNOTOIDA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SUDUNGQUYDINH" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.THUTIEN" Member="THUTIENs">
    <Type Name="THUTIEN">
      <Column Name="MATHU" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="NGAYTHU" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SOTIENTHU" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="KHACHHANG_THUTIEN" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
</Database>